name: Kotlin Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build project
      run: ./gradlew clean build

    - name: Test project
      run: ./gradlew test

    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: charlesdeguo/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    -name: docker build
      run: make build-docker

    -name: docker push
      run: docker push ${{secrets.DOCKER_USER}}/charlesdeguo