name: Kotlin Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Test project
      run: make test

    - name: Build project
      run: make build
