name: Kotlin Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Test project
      run: make test

    - name: Build project
      run: make build
